apiVersion: apps/v1
kind: Deployment
metadata:
  name: pfe-backend
  labels:
    app: pfe-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pfe-backend
  template:
    metadata:
      labels:
        app: pfe-backend
    spec:
      containers:
        - name: pfe-backend
          image: khalilkh/pfe-back:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb+srv://khalilkhemiri681:wZVeAfkhbsHQnav3@cluster0.nlrnvnq.mongodb.net/mygrocerylist?retryWrites=true&w=majority&tls=true&appName=Cluster0"
            - name: SPRING_DATA_MONGODB_DATABASE
              value: "pfe"
